ALTER TABLE jobs ADD COLUMN IF NOT EXISTS started_at           TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS finished_at          TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS duration_ms          BIGINT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_percent     DOUBLE PRECISION;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_label       TEXT        NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_is_estimate BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_updated_at  TIMESTAMPTZ;

ALTER TABLE media ADD COLUMN IF NOT EXISTS runtime_snapshot_json TEXT NOT NULL DEFAULT '';
